sudo: false

os:
  - osx

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./src/main/cpp/tests/runUnitTests

notifications:
  email: false